apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: teamskcafeforme 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: teamskcafeforme 
    spec:
      containers:
        - name: teamskcafeforme 
          image: lkkacr.azurecr.io/teamskcafeforme
          ports:
          - containerPort: 8080